export const treeData = [
  {
    id: 'A',
    name: 'Addis Ababa',
    sortNo: 'A',
    parentId: '0',
    children: [
      {
        id: 'A01',
        name: 'North Addis Ababa District',
        sortNo: 'A01',
        parentId: 'A',
        children: [
          {
            id: 'A011',
            name: 'NORTH AA CSC NO.1',
            sortNo: 'A011',
            parentId: 'A01',
          },
          {
            id: 'A012',
            name: 'NORTH AA CSC NO.2',
            sortNo: 'A012',
            parentId: 'A01',
          },
          {
            id: 'A013',
            name: 'NORTH AA CSC NO.3',
            sortNo: 'A013',
            parentId: 'A01',
          },
          {
            id: 'A014',
            name: 'NORTH AA CSC NO.4',
            sortNo: 'A014',
            parentId: 'A01',
          },
          {
            id: 'A015',
            name: 'NORTH AA CSC NO.5',
            sortNo: 'A015',
            parentId: 'A01',
          },
        ],
      },
      {
        id: 'A02',
        name: 'East Addis Ababa District',
        sortNo: 'A02',
        parentId: 'A',
        children: [
          {
            id: 'A021',
            name: 'EAST AA CSC NO.1',
            sortNo: 'A021',
            parentId: 'A02',
          },
          {
            id: 'A022',
            name: 'EAST AA CSC NO.2',
            sortNo: 'A022',
            parentId: 'A02',
          },
          {
            id: 'A023',
            name: 'EAST AA CSC NO.3',
            sortNo: 'A023',
            parentId: 'A02',
          },
          {
            id: 'A024',
            name: 'EAST AA CSC NO.4',
            sortNo: 'A024',
            parentId: 'A02',
          },
          {
            id: 'A025',
            name: 'EAST AA CSC NO.5',
            sortNo: 'A025',
            parentId: 'A02',
          },
          {
            id: 'A026',
            name: 'EAST AA CSC NO.6',
            sortNo: 'A026',
            parentId: 'A05',
          },
          {
            id: 'A027',
            name: 'EAST AA CSC NO.7',
            sortNo: 'A027',
            parentId: 'A02',
          },
          {
            id: 'A028',
            name: 'EAST AA CSC NO.8',
            sortNo: 'A028',
            parentId: 'A02',
          },
          {
            id: 'A029',
            name: 'EAST AA CSC NO.9',
            sortNo: 'A029',
            parentId: 'A02',
          },
        ],
      },
      {
        id: 'A03',
        name: 'West Addis Ababa District',
        sortNo: 'A03',
        parentId: 'A',
        children: [
          {
            id: 'A031',
            name: 'WEST AA CSC NO.1',
            sortNo: 'A031',
            parentId: 'A03',
          },
          {
            id: 'A032',
            name: 'WEST AA CSC NO.2',
            sortNo: 'A032',
            parentId: 'A03',
          },
          {
            id: 'A033',
            name: 'WEST AA CSC NO.3',
            sortNo: 'A033',
            parentId: 'A03',
          },
          {
            id: 'A034',
            name: 'WEST AA CSC NO.4',
            sortNo: 'A034',
            parentId: 'A03',
          },
          {
            id: 'A035',
            name: 'WEST AA CSC NO.5',
            sortNo: 'A035',
            parentId: 'A03',
          },
          {
            id: 'A036',
            name: 'WEST AA CSC NO.6',
            sortNo: 'A036',
            parentId: 'A03',
          },
          {
            id: 'A037',
            name: 'WEST AA CSC NO.7',
            sortNo: 'A037',
            parentId: 'A03',
          },
          {
            id: 'A038',
            name: 'WEST AA CSC NO.8',
            sortNo: 'A038',
            parentId: 'A03',
          },
        ],
      },
      {
        id: 'A04',
        name: 'SOUTH Addis Ababa District',
        sortNo: 'A04',
        parentId: 'A',
        children: [
          {
            id: 'A041',
            name: 'SOUTH AA CSC NO.1',
            sortNo: 'A041',
            parentId: 'A04',
          },
          {
            id: 'A042',
            name: 'SOUTH AA CSC NO.2',
            sortNo: 'A042',
            parentId: 'A04',
          },
          {
            id: 'A043',
            name: 'SOUTH AA CSC NO.3',
            sortNo: 'A043',
            parentId: 'A04',
          },
          {
            id: 'A044',
            name: 'SOUTH AA CSC NO.4',
            sortNo: 'A044',
            parentId: 'A04',
          },
          {
            id: 'A045',
            name: 'SOUTH AA CSC NO.5',
            sortNo: 'A045',
            parentId: 'A04',
          },
          {
            id: 'A046',
            name: 'SOUTH AA CSC NO.6',
            sortNo: 'A046',
            parentId: 'A05',
          },
          {
            id: 'A047',
            name: 'SOUTH AA CSC NO.7',
            sortNo: 'A047',
            parentId: 'A04',
          },
          {
            id: 'A048',
            name: 'SOUTH AA CSC NO.8',
            sortNo: 'A048',
            parentId: 'A04',
          },
          {
            id: 'A049',
            name: 'SOUTH AA CSC NO.9',
            sortNo: 'A049',
            parentId: 'A04',
          },
          {
            id: 'A0410',
            name: 'South AA CSC NO.10',
            sortNo: 'A0410',
            parentId: 'A04',
          },
        ],
      },
    ],
  },
  {
    id: 'B',
    name: 'Oromia Region',
    sortNo: 'B',
    parentId: '0',
    children: [
            {
        id: 'B02',
        name: 'Adama District',
        sortNo: 'B02',
        parentId: 'B',
        children: [
          {
            id: 'B021',
            name: 'ADAMA NO 1',
            sortNo: 'B021',
            parentId: 'B02',
          },
          {
            id: 'B022',
            name: 'ADAMA NO 2',
            sortNo: 'B022',
            parentId: 'B02',
          },
          {
            id: 'B023',
            name: 'ADAMA NO 3',
            sortNo: 'B023',
            parentId: 'B02',
          },
          {
            id: 'B024',
            name: 'ADAMA NO 4',
            sortNo: 'B024',
            parentId: 'B02',
          },
          {
            id: 'B025',
            name: 'ABOMSA',
            sortNo: 'B025',
            parentId: 'B02',
          },
          {
            id: 'B026',
            name: 'ADAMITULU',
            sortNo: 'B026',
            parentId: 'B02',
          },
          {
            id: 'B027',
            name: 'BEKOJI',
            sortNo: 'B027',
            parentId: 'B02',
          },
          {
            id: 'B028',
            name: 'BULBULA',
            sortNo: 'B028',
            parentId: 'B02',
          },
          {
            id: 'B029',
            name: 'DERA',
            sortNo: 'B029',
            parentId: 'B02',
          },
          {
            id: 'B0210',
            name: 'KERSA',
            sortNo: 'B0210',
            parentId: 'B02',
          },

          {
            id: 'B0211',
            name: 'AWASH MELKASA',
            sortNo: 'B0211',
            parentId: 'B02',
          },
          {
            id: 'B0212',
            name: 'SAGURE',
            sortNo: 'B0212',
            parentId: 'B02',
          },
          {
            id: 'B0213',
            name: 'WELENCHITI',
            sortNo: 'B0213',
            parentId: 'B02',
          },
          {
            id: 'B0214',
            name: 'WONJI',
            sortNo: 'B0214',
            parentId: 'B02',
          },
          {
            id: 'B0215',
            name: 'ASSELA',
            sortNo: 'B0215',
            parentId: 'B02',
          },
          {
            id: 'B0216',
            name: 'METEHARA',
            sortNo: 'B0216',
            parentId: 'B02',
          },
          {
            id: 'B0217',
            name: 'MOJO',
            sortNo: 'B0217',
            parentId: 'B02',
          },
          {
            id: 'B0218',
            name: 'ZEWAY',
            sortNo: 'B0218',
            parentId: 'B02',
          },
          {
            id: 'B0219',
            name: 'GOBESA',
            sortNo: 'B0219',
            parentId: 'B02',
          },
          {
            id: 'B0220',
            name: 'ARSI ROBE',
            sortNo: 'B0220',
            parentId: 'B02',
          },
          {
            id: 'B0221',
            name: 'ALEM TENA',
            sortNo: 'B0221',
            parentId: 'B02',
          },
          {
            id: 'B0222',
            name: 'ETEYA',
            sortNo: 'B0222',
            parentId: 'B02',
          },
          {
            id: 'B0223',
            name: 'CHOLE',
            sortNo: 'B0223',
            parentId: 'B02',
          },
          {
            id: 'B0224',
            name: 'OGOLCHO',
            sortNo: 'B0224',
            parentId: 'B02',
          },
          {
            id: 'B0225',
            name: 'DEKESIS',
            sortNo: 'B0225',
            parentId: 'B02',
          },
          {
            id: 'B0226',
            name: 'HURUTA',
            sortNo: 'B0226',
            parentId: 'B02',
          },
          {
            id: 'B0227',
            name: 'MEKI',
            sortNo: 'B0227',
            parentId: 'B02',
          },
          {
            id: 'B0228',
            name: 'ASELA NO 2',
            sortNo: 'B0228',
            parentId: 'B02',
          },
          {
            id: 'B0229',
            name: 'BELE',
            sortNo: 'B0229',
            parentId: 'B02',
          },
          {
            id: 'B0230',
            name: 'ARBOYE',
            sortNo: 'B0230',
            parentId: 'B02',
          },
        ],
      },
      {
        id: 'B03',
        name: 'Ambo District',
        sortNo: 'B03',
        parentId: 'B',
        children: [
          {
            id: 'B031',
            name: 'AMBO',
            sortNo: 'B031',
            parentId: 'B03',
          },
          {
            id: 'B032',
            name: 'TULUBOLO',
            sortNo: 'B032',
            parentId: 'B03',
          },
          {
            id: 'B033',
            name: 'WELISO',
            sortNo: 'B033',
            parentId: 'B03',
          },
          {
            id: 'B034',
            name: 'BANYU',
            sortNo: 'B034',
            parentId: 'B03',
          },
          {
            id: 'B035',
            name: 'AMAYA',
            sortNo: 'B035',
            parentId: 'B03',
          },
          {
            id: 'B036',
            name: 'ADDIS ALEM',
            sortNo: 'B036',
            parentId: 'B03',
          },
          {
            id: 'B037',
            name: 'GINCHI',
            sortNo: 'B037',
            parentId: 'B03',
          },
          {
            id: 'B038',
            name: 'KACHISI',
            sortNo: 'B038',
            parentId: 'B03',
          },
          {
            id: 'B039',
            name: 'GUDER',
            sortNo: 'B039',
            parentId: 'B03',
          },
          {
            id: 'B0310',
            name: 'HORMAT',
            sortNo: 'B0310',
            parentId: 'B03',
          },
          {
            id: 'B0311',
            name: 'GEDO',
            sortNo: 'B0311',
            parentId: 'B03',
          },
          {
            id: 'B0312',
            name: 'EJAJI',
            sortNo: 'B0312',
            parentId: 'B03',
          },
          {
            id: 'B0313',
            name: 'BAKO',
            sortNo: 'B0313',
            parentId: 'B03',
          },
          {
            id: 'B0314',
            name: 'WAYU',
            sortNo: 'B0314',
            parentId: 'B03',
          },

          {
            id: 'B0315',
            name: 'JELDU',
            sortNo: 'B0315',
            parentId: 'B03',
          },
          {
            id: 'B0316',
            name: 'SEYO',
            sortNo: 'B0316',
            parentId: 'B03',
          },
          {
            id: 'B0317',
            name: 'SEDENSODO',
            sortNo: 'B0317',
            parentId: 'B03',
          },
          {
            id: 'B0318',
            name: 'ABUNA',
            sortNo: 'B0318',
            parentId: 'B03',
          },
          {
            id: 'B0319',
            name: 'SHENEN',
            sortNo: 'B0319',
            parentId: 'B03',
          },
          {
            id: 'B0320',
            name: 'BILO',
            sortNo: 'B0320',
            parentId: 'B03',
          },
          {
            id: 'B0321',
            name: 'BUSA',
            sortNo: 'B0321',
            parentId: 'B03',
          },
          {
            id: 'B0322',
            name: 'SILKAMBA',
            sortNo: 'B0322',
            parentId: 'B03',
          },
        ],
      },
      {
        id: 'B04',
        name: 'Bale Robe District',
        sortNo: 'B04',
        parentId: 'B',
        children: [
          {
            id: 'B041',
            name: 'ROBE',
            sortNo: 'B041',
            parentId: 'B04',
          },
          {
            id: 'B042',
            name: 'BALE GOBA',
            sortNo: 'B042',
            parentId: 'B04',
          },
          {
            id: 'B043',
            name: 'ADABA',
            sortNo: 'B043',
            parentId: 'B04',
          },
          {
            id: 'B044',
            name: 'AGARFA',
            sortNo: 'B044',
            parentId: 'B04',
          },
          {
            id: 'B045',
            name: 'GASERA',
            sortNo: 'B045',
            parentId: 'B04',
          },
          {
            id: 'B046',
            name: 'GORO',
            sortNo: 'B046',
            parentId: 'B04',
          },
          {
            id: 'B047',
            name: 'DELOMENA',
            sortNo: 'B047',
            parentId: 'B04',
          },
          {
            id: 'B048',
            name: 'HARA DUMELE',
            sortNo: 'B048',
            parentId: 'B04',
          },
          {
            id: 'B049',
            name: 'RAYITU/CHERECHER',
            sortNo: 'B049',
            parentId: 'B04',
          },
          {
            id: 'B0410',
            name: 'DINSHO',
            sortNo: 'B0410',
            parentId: 'B04',
          },
          {
            id: 'B0411',
            name: 'WERKA',
            sortNo: 'B0411',
            parentId: 'B04',
          },
          {
            id: 'B0412',
            name: 'JARA',
            sortNo: 'B0412',
            parentId: 'B04',
          },
        ],
      },

      {
        id: 'B05',
        name: 'Chiro District',
        sortNo: 'B05',
        parentId: 'B',
        children: [
          {
            id: 'B051',
            name: 'CHIRO',
            sortNo: 'B051',
            parentId: 'B05',
          },
          {
            id: 'B052',
            name: 'BABILA',
            sortNo: 'B052',
            parentId: 'B05',
          },
          {
            id: 'B053',
            name: 'BEDASA',
            sortNo: 'B053',
            parentId: 'B05',
          },
          {
            id: 'B054',
            name: 'BISIDUMO',
            sortNo: 'B054',
            parentId: 'B05',
          },
          {
            id: 'B055',
            name: 'KOMBOLCHA',
            sortNo: 'B055',
            parentId: 'B05',
          },
          {
            id: 'B056',
            name: 'GELEMSA',
            sortNo: 'B056',
            parentId: 'B05',
          },
          {
            id: 'B057',
            name: 'GURSUM',
            sortNo: 'B057',
            parentId: 'B05',
          },
          {
            id: 'B058',
            name: 'HIRNA',
            sortNo: 'B058',
            parentId: 'B05',
          },
          {
            id: 'B059',
            name: 'KARAMILE',
            sortNo: 'B059',
            parentId: 'B05',
          },
          {
            id: 'B0510',
            name: 'KERSA',
            sortNo: 'B0510',
            parentId: 'B05',
          },
          {
            id: 'B0511',
            name: 'DEDER',
            sortNo: 'B0511',
            parentId: 'B05',
          },
          {
            id: 'B0512',
            name: 'HAROMAYA',
            sortNo: 'B0512',
            parentId: 'B05',
          },

          {
            id: 'B0513',
            name: 'GERAWA',
            sortNo: 'B0513',
            parentId: 'B05',
          },
          {
            id: 'B0514',
            name: 'MECHARA',
            sortNo: 'B0514',
            parentId: 'B05',
          },
          {
            id: 'B0515',
            name: 'MEASO',
            sortNo: 'B0515',
            parentId: 'B05',
          },
          {
            id: 'B0516',
            name: 'CHENAGESAN',
            sortNo: 'B0516',
            parentId: 'B05',
          },
          {
            id: 'B0517',
            name: 'FEDIS',
            sortNo: 'B0517',
            parentId: 'B05',
          },
          {
            id: 'B0518',
            name: 'AWEDAYE',
            sortNo: 'B0518',
            parentId: 'B05',
          },
        ],
      },
      {
        id: 'B06',
        name: 'Finfine Zuria District',
        sortNo: 'B06',
        parentId: 'B',
        children: [
          {
            id: 'B061',
            name: 'SENDAFA',
            sortNo: 'B061',
            parentId: 'B06',
          },
          {
            id: 'B062',
            name: 'SHENO',
            sortNo: 'B062',
            parentId: 'B06',
          },
          {
            id: 'B063',
            name: 'MUKETURI',
            sortNo: 'B063',
            parentId: 'B06',
          },
          {
            id: 'B064',
            name: 'FICHE',
            sortNo: 'B064',
            parentId: 'B06',
          },
          {
            id: 'B065',
            name: 'GEBREGURACHA',
            sortNo: 'B065',
            parentId: 'B06',
          },
          {
            id: 'B066',
            name: 'EJERE',
            sortNo: 'B066',
            parentId: 'B06',
          },
          {
            id: 'B067',
            name: 'GUNDOMESKEL',
            sortNo: 'B067',
            parentId: 'B06',
          },
          {
            id: 'B068',
            name: 'LEGETAFO',
            sortNo: 'B068',
            parentId: 'B06',
          },
          {
            id: 'B069',
            name: 'GOHATSION',
            sortNo: 'B069',
            parentId: 'B06',
          },
          {
            id: 'B0610',
            name: 'BURAYU',
            sortNo: 'B0610',
            parentId: 'B06',
          },

          {
            id: 'B0611',
            name: 'TERE',
            sortNo: 'B0611',
            parentId: 'B06',
          },
          {
            id: 'B0612',
            name: 'CHANCO',
            sortNo: 'B0612',
            parentId: 'B06',
          },
          {
            id: 'B0613',
            name: 'HOLETA',
            sortNo: 'B0613',
            parentId: 'B06',
          },
          {
            id: 'B0614',
            name: 'MUGER',
            sortNo: 'B0614',
            parentId: 'B06',
          },
          {
            id: 'B0615',
            name: 'SULULTA',
            sortNo: 'B0615',
            parentId: 'B06',
          },
          {
            id: 'B0616',
            name: 'TATEKE',
            sortNo: 'B0616',
            parentId: 'B06',
          },
          {
            id: 'B0617',
            name: 'DUKEM',
            sortNo: 'B0617',
            parentId: 'B06',
          },
          {
            id: 'B0618',
            name: 'BISHOFTU NO 1',
            sortNo: 'B0618',
            parentId: 'B06',
          },
          {
            id: 'B0619',
            name: 'BISHOFTU NO 2',
            sortNo: 'B0619',
            parentId: 'B06',
          },
          {
            id: 'B0620',
            name: 'CHEFE DONSA',
            sortNo: 'B0620',
            parentId: 'B06',
          },
          {
            id: 'B0621',
            name: 'ADULALA',
            sortNo: 'B0621',
            parentId: 'B06',
          },
          {
            id: 'B0622',
            name: 'GELAN',
            sortNo: 'B0622',
            parentId: 'B06',
          },
          {
            id: 'B0623',
            name: 'SEBETA',
            sortNo: 'B0623',
            parentId: 'B06',
          },
          {
            id: 'B0624',
            name: 'ALEMGENA',
            sortNo: 'B0624',
            parentId: 'B06',
          },
          {
            id: 'B0625',
            name: 'FURI',
            sortNo: 'B0625',
            parentId: 'B06',
          },
          {
            id: 'B0626',
            name: 'ANFO MEDA',
            sortNo: 'B0626',
            parentId: 'B06',
          },
          {
            id: 'B0627',
            name: 'LEMEN',
            sortNo: 'B0627',
            parentId: 'B06',
          },
          {
            id: 'B0628',
            name: 'OROMIA CONDOMINIUM',
            sortNo: 'B0628',
            parentId: 'B06',
          },
          {
            id: 'B0629',
            name: 'SHINO',
            sortNo: 'B0629',
            parentId: 'B06',
          },
        ],
      },
      {
        id: 'B07',
        name: 'Jima District',
        sortNo: 'B07',
        parentId: 'B',
        children: [
          {
            id: 'B071',
            name: 'JIMMA NO 1',
            sortNo: 'B071',
            parentId: 'B07',
          },
          {
            id: 'B072',
            name: 'JIMMA NO 2',
            sortNo: 'B072',
            parentId: 'B07',
          },
          {
            id: 'B073',
            name: 'ASENDIBO',
            sortNo: 'B073',
            parentId: 'B07',
          },
          {
            id: 'B074',
            name: 'LIMMU',
            sortNo: 'B074',
            parentId: 'B07',
          },
          {
            id: 'B075',
            name: 'TOBA',
            sortNo: 'B075',
            parentId: 'B07',
          },
          {
            id: 'B076',
            name: 'SOKORO',
            sortNo: 'B076',
            parentId: 'B07',
          },
          {
            id: 'B077',
            name: 'AGARO',
            sortNo: 'B077',
            parentId: 'B07',
          },
          {
            id: 'B078',
            name: 'DUMTU',
            sortNo: 'B078',
            parentId: 'B07',
          },
          {
            id: 'B079',
            name: 'GATIRA',
            sortNo: 'B079',
            parentId: 'B07',
          },
          {
            id: 'B0710',
            name: 'GERA',
            sortNo: 'B0710',
            parentId: 'B07',
          },
          {
            id: 'B0711',
            name: 'DEDO',
            sortNo: 'B0711',
            parentId: 'B07',
          },
          {
            id: 'B0712',
            name: 'SHEBE',
            sortNo: 'B0712',
            parentId: 'B07',
          },
          {
            id: 'B0713',
            name: 'AGRO NO 2',
            sortNo: 'B0713',
            parentId: 'B07',
          },
          {
            id: 'B0714',
            name: 'DEMBI',
            sortNo: 'B0714',
            parentId: 'B07',
          },

          {
            id: 'B0715',
            name: 'CHORA',
            sortNo: 'B0715',
            parentId: 'B07',
          },
          {
            id: 'B0716',
            name: 'BEDELAE',
            sortNo: 'B0716',
            parentId: 'B07',
          },
          {
            id: 'B0717',
            name: 'CHEWAKA',
            sortNo: 'B0717',
            parentId: 'B07',
          },
        ],
      },
      {
        id: 'B08',
        name: 'Metu District',
        sortNo: 'B08',
        parentId: 'B',
        children: [
          {
            id: 'B081',
            name: 'METU',
            sortNo: 'B081',
            parentId: 'B08',
          },
          {
            id: 'B082',
            name: 'GORE',
            sortNo: 'B082',
            parentId: 'B08',
          },
          {
            id: 'B083',
            name: 'SUPI',
            sortNo: 'B083',
            parentId: 'B08',
          },
          {
            id: 'B084',
            name: 'YAYU',
            sortNo: 'B084',
            parentId: 'B08',
          },
          {
            id: 'B085',
            name: 'BURE',
            sortNo: 'B085',
            parentId: 'B08',
          },
          {
            id: 'B086',
            name: 'DURENI',
            sortNo: 'B086',
            parentId: 'B08',
          },
          {
            id: 'B087',
            name: 'DIREMU',
            sortNo: 'B087',
            parentId: 'B08',
          },
          {
            id: 'B088',
            name: 'DEGA',
            sortNo: 'B088',
            parentId: 'B08',
          },
          {
            id: 'B089',
            name: 'HURMU',
            sortNo: 'B089',
            parentId: 'B08',
          },
          {
            id: 'B0810',
            name: 'NOPA',
            sortNo: 'B0810',
            parentId: 'B08',
          },
          {
            id: 'B0811',
            name: 'BECHO',
            sortNo: 'B0811',
            parentId: 'B08',
          },
          {
            id: 'B0812',
            name: 'SELE NONO',
            sortNo: 'B0812',
            parentId: 'B08',
          },
          {
            id: 'B0813',
            name: 'LALO',
            sortNo: 'B0813',
            parentId: 'B08',
          },
        ],
      },

      {
        id: 'B09',
        name: 'Nekemt District',
        sortNo: 'B09',
        parentId: 'B',
        children: [
          {
            id: 'B091',
            name: 'NEKEMT',
            sortNo: 'B091',
            parentId: 'B09',
          },
          {
            id: 'B092',
            name: 'FINCHA',
            sortNo: 'B092',
            parentId: 'B09',
          },
          {
            id: 'B093',
            name: 'SHAMBU',
            sortNo: 'B093',
            parentId: 'B09',
          },
          {
            id: 'B094',
            name: 'ALIBO',
            sortNo: 'B094',
            parentId: 'B09',
          },
          {
            id: 'B095',
            name: 'MECHARA',
            sortNo: 'B095',
            parentId: 'B09',
          },
          {
            id: 'B096',
            name: 'MUGI',
            sortNo: 'B096',
            parentId: 'B09',
          },
          {
            id: 'B097',
            name: 'ROBGEBEYA',
            sortNo: 'B097',
            parentId: 'B09',
          },
          {
            id: 'B098',
            name: 'DEMBIDOLLO',
            sortNo: 'B098',
            parentId: 'B09',
          },
          {
            id: 'B099',
            name: 'NEGI',
            sortNo: 'B099',
            parentId: 'B09',
          },
          {
            id: 'B0910',
            name: 'GULISO',
            sortNo: 'B0910',
            parentId: 'B09',
          },
          {
            id: 'B0911',
            name: 'MENDI',
            sortNo: 'B0911',
            parentId: 'B09',
          },
          {
            id: 'B0912',
            name: 'NEDJO',
            sortNo: 'B0912',
            parentId: 'B09',
          },

          {
            id: 'B0913',
            name: 'GHIMBI',
            sortNo: 'B0913',
            parentId: 'B09',
          },
          {
            id: 'B0914',
            name: 'HAROSEBU',
            sortNo: 'B0914',
            parentId: 'B09',
          },
          {
            id: 'B0915',
            name: 'NOLEKABA',
            sortNo: 'B0915',
            parentId: 'B09',
          },
          {
            id: 'B0916',
            name: 'GIDA AYANA',
            sortNo: 'B0916',
            parentId: 'B09',
          },
          {
            id: 'B0917',
            name: 'SIRE',
            sortNo: 'B0917',
            parentId: 'B09',
          },
          {
            id: 'B0918',
            name: 'ANGER GUTIN',
            sortNo: 'B0918',
            parentId: 'B09',
          },

          {
            id: 'B0919',
            name: 'KIRAMU',
            sortNo: 'B0919',
            parentId: 'B09',
          },
          {
            id: 'B0920',
            name: 'ARJO',
            sortNo: 'B0920',
            parentId: 'B09',
          },
          {
            id: 'B0921',
            name: 'DEDU',
            sortNo: 'B0921',
            parentId: 'B09',
          },
          {
            id: 'B0922',
            name: 'SASIGA',
            sortNo: 'B0922',
            parentId: 'B09',
          },
          {
            id: 'B0923',
            name: 'UKE',
            sortNo: 'B0923',
            parentId: 'B09',
          },
          {
            id: 'B0924',
            name: 'ARJO GUDUTU',
            sortNo: 'B0924',
            parentId: 'B09',
          },
          {
            id: 'B0925',
            name: 'NUNU KUMBA',
            sortNo: 'B0925',
            parentId: 'B09',
          },
          {
            id: 'B0926',
            name: 'OBERA',
            sortNo: 'B0926',
            parentId: 'B09',
          },
          {
            id: 'B0927',
            name: 'NEKEMT NO 2',
            sortNo: 'B0927',
            parentId: 'B09',
          },
          {
            id: 'B0928',
            name: 'GENJI',
            sortNo: 'B0928',
            parentId: 'B09',
          },
          {
            id: 'B0929',
            name: 'HARO',
            sortNo: 'B0929',
            parentId: 'B09',
          },
          {
            id: 'B0930',
            name: 'KAKE',
            sortNo: 'B0930',
            parentId: 'B09',
          },
        ],
      },
      {
        id: 'B010',
        name: 'Shashemene District',
        sortNo: 'B010',
        parentId: 'B',
        children: [
          {
            id: 'B0101',
            name: 'SHASHEMENE NO 1',
            sortNo: 'B0101',
            parentId: 'B010',
          },
          {
            id: 'B0102',
            name: 'SHASHEMENE NO 2',
            sortNo: 'B0102',
            parentId: 'B010',
          },
          {
            id: 'B0103',
            name: 'BORE',
            sortNo: 'B0103',
            parentId: 'B010',
          },
          {
            id: 'B0104',
            name: 'H / MARIAM',
            sortNo: 'B0104',
            parentId: 'B010',
          },
          {
            id: 'B0105',
            name: 'KOFELE',
            sortNo: 'B0105',
            parentId: 'B010',
          },
          {
            id: 'B0106',
            name: 'N / BORENEA',
            sortNo: 'B0106',
            parentId: 'B010',
          },
          {
            id: 'B0107',
            name: 'SHAKISO',
            sortNo: 'B0107',
            parentId: 'B010',
          },
          {
            id: 'B0108',
            name: 'YABELO',
            sortNo: 'B0108',
            parentId: 'B010',
          },
          {
            id: 'B0109',
            name: 'ARISI NEGELE',
            sortNo: 'B0109',
            parentId: 'B010',
          },
          {
            id: 'B01010',
            name: 'KIBER MENGISTU',
            sortNo: 'B01010',
            parentId: 'B010',
          },

          {
            id: 'B01011',
            name: 'TERE',
            sortNo: 'MOYALE',
            parentId: 'B010',
          },
          {
            id: 'B01012',
            name: 'SOLOMO',
            sortNo: 'B01012',
            parentId: 'B010',
          },
          {
            id: 'B01013',
            name: 'TORE',
            sortNo: 'B01013',
            parentId: 'B010',
          },
          {
            id: 'B01014',
            name: 'COCOSA',
            sortNo: 'B01014',
            parentId: 'B010',
          },
          {
            id: 'B01015',
            name: 'BISHAN GURACA',
            sortNo: 'B01015',
            parentId: 'B010',
          },
          {
            id: 'B01016',
            name: 'GUANGO',
            sortNo: 'B01016',
            parentId: 'B010',
          },
          {
            id: 'B01017',
            name: 'KERCHA',
            sortNo: 'B01017',
            parentId: 'B010',
          },
          {
            id: 'B01018',
            name: 'ADJE',
            sortNo: 'B01018',
            parentId: 'B010',
          },
          {
            id: 'B01019',
            name: 'MEGA',
            sortNo: 'B01019',
            parentId: 'B010',
          },
          {
            id: 'B01020',
            name: 'GOLJOTA',
            sortNo: 'B01020',
            parentId: 'B010',
          },
          {
            id: 'B01021',
            name: 'HEREKELO',
            sortNo: 'B01021',
            parentId: 'B010',
          },
          {
            id: 'B01022',
            name: 'BIDIRE',
            sortNo: 'B01022',
            parentId: 'B010',
          },
          {
            id: 'B01023',
            name: 'DIMTU6',
            sortNo: 'B01023',
            parentId: 'B010',
          },
          {
            id: 'B01024',
            name: 'MELKA SODA',
            sortNo: 'B01024',
            parentId: 'B010',
          },
          {
            id: 'B01025',
            name: 'ASASA',
            sortNo: 'B01025',
            parentId: 'B010',
          },
        ],
      },
    ],
  },

  {
    id: 'C',
    name: 'Amhara',
    sortNo: 'C',
    parentId: '0',
    children: [
      {
        id: 'C01',
        name: 'Bahir Dar District',
        sortNo: 'C01',
        parentId: 'C',
        children: [
          {
            id: 'C011',
            name: 'BAHIR DAR 1',
            sortNo: 'C011',
            parentId: 'C01',
          },
          {
            id: 'C012',
            name: 'BAHIR DAR 2',
            sortNo: 'C012',
            parentId: 'C01',
          },
          {
            id: 'C013',
            name: 'ADET',
            sortNo: 'C013',
            parentId: 'C01',
          },
          {
            id: 'C014',
            name: 'CHAGNI',
            sortNo: 'C014',
            parentId: 'C01',
          },
          {
            id: 'C015',
            name: 'DURBETIE',
            sortNo: 'C015',
            parentId: 'C01',
          },
          {
            id: 'C016',
            name: 'KOSSOBER',
            sortNo: 'C016',
            parentId: 'C01',
          },
          {
            id: 'C017',
            name: 'MERAWI',
            sortNo: 'C017',
            parentId: 'C01',
          },
          {
            id: 'C018',
            name: 'WORETA',
            sortNo: 'C018',
            parentId: 'C01',
          },
          {
            id: 'C019',
            name: 'DANGLIA',
            sortNo: 'C019',
            parentId: 'C01',
          },
          {
            id: 'C0110',
            name: 'DEBERE TABOR',
            sortNo: 'C0110',
            parentId: 'C01',
          },
          {
            id: 'C0111',
            name: 'EBNAT',
            sortNo: 'C0111',
            parentId: 'C01',
          },
          {
            id: 'C0112',
            name: 'JAWI',
            sortNo: 'C0112',
            parentId: 'C01',
          },

          {
            id: 'C0113',
            name: 'ESTI',
            sortNo: 'C0113',
            parentId: 'C01',
          },
          {
            id: 'C0114',
            name: 'ADDIS ZEMEN',
            sortNo: 'C0114',
            parentId: 'C01',
          },
          {
            id: 'C0115',
            name: 'WEGEDA',
            sortNo: 'C0115',
            parentId: 'C01',
          },
          {
            id: 'C0116',
            name: 'GISHABAY',
            sortNo: 'C0116',
            parentId: 'C01',
          },
          {
            id: 'C0117',
            name: 'ADDISKEDAM',
            sortNo: 'C0117',
            parentId: 'C01',
          },
          {
            id: 'C0118',
            name: 'LIBEN CSC',
            sortNo: 'C0118',
            parentId: 'C01',
          },
          {
            id: 'C0119',
            name: 'KILAJ',
            sortNo: 'C0119',
            parentId: 'C01',
          },
          {
            id: 'C0120',
            name: 'AMBESAME',
            sortNo: 'C0120',
            parentId: 'C01',
          },
          {
            id: 'C0121',
            name: 'NEFAS MEWUCHA',
            sortNo: 'C0121',
            parentId: 'C01',
          },
          {
            id: 'C0122',
            name: 'DEBRETABOR 2',
            sortNo: 'C0122',
            parentId: 'C01',
          },
          {
            id: 'C0123',
            name: 'KIMIRDINGAY',
            sortNo: 'C0123',
            parentId: 'C01',
          },
          {
            id: 'C0124',
            name: 'GONJI',
            sortNo: 'C0124',
            parentId: 'C01',
          },
          {
            id: 'C0125',
            name: 'BAHIR DAR 3 CSC',
            sortNo: 'C0125',
            parentId: 'C01',
          },
          {
            id: 'C0126',
            name: 'Tach gaynt(Arib Gebeya)',
            sortNo: 'C0126',
            parentId: 'C01',
          },
          {
            id: 'C0127',
            name: 'ANDABET',
            sortNo: 'C0127',
            parentId: 'C01',
          },
          {
            id: 'C0128',
            name: 'GEMEJABET',
            sortNo: 'C0128',
            parentId: 'C01',
          },
        ],
      },
      {
        id: 'C02',
        name: 'Dese District',
        sortNo: 'C02',
        parentId: 'C',
        children: [
          {
            id: 'C021',
            name: 'DESSIE 1',
            sortNo: 'C021',
            parentId: 'C02',
          },
          {
            id: 'C022',
            name: 'DESSIE 2',
            sortNo: 'C022',
            parentId: 'C02',
          },
          {
            id: 'C023',
            name: 'BATI',
            sortNo: 'C023',
            parentId: 'C02',
          },
          {
            id: 'C024',
            name: 'AKESTA',
            sortNo: 'C024',
            parentId: 'C02',
          },
          {
            id: 'C025',
            name: 'HALK',
            sortNo: 'C025',
            parentId: 'C02',
          },
          {
            id: 'C026',
            name: 'MEKANESELAM',
            sortNo: 'C026',
            parentId: 'C02',
          },
          {
            id: 'C027',
            name: 'TENTA',
            sortNo: 'C027',
            parentId: 'C02',
          },
          {
            id: 'C028',
            name: 'WERILU',
            sortNo: 'C028',
            parentId: 'C02',
          },
          {
            id: 'C029',
            name: 'KEMISSE',
            sortNo: 'C029',
            parentId: 'C02',
          },
          {
            id: 'C0210',
            name: 'KOMBOLCHA NO.1',
            sortNo: 'C0210',
            parentId: 'C02',
          },

          {
            id: 'C0211',
            name: 'KOMBOLCHA NO.2',
            sortNo: 'C0211',
            parentId: 'C02',
          },
          {
            id: 'C0212',
            name: 'SAINT AJIBAR',
            sortNo: 'C0212',
            parentId: 'C02',
          },
          {
            id: 'C0213',
            name: 'KUTABER',
            sortNo: 'C0213',
            parentId: 'C02',
          },
          {
            id: 'C0214',
            name: 'WEGDI',
            sortNo: 'C0214',
            parentId: 'C02',
          },
          {
            id: 'C0215',
            name: 'WUCHALE',
            sortNo: 'C0215',
            parentId: 'C02',
          },
          {
            id: 'C0216',
            name: 'KELALA',
            sortNo: 'C0216',
            parentId: 'C02',
          },
          {
            id: 'C0217',
            name: 'WEGL TENA',
            sortNo: 'C0217',
            parentId: 'C02',
          },
          {
            id: 'C0218',
            name: 'ALBKO',
            sortNo: 'C0218',
            parentId: 'C02',
          },
          {
            id: 'C0219',
            name: 'BISTIMA',
            sortNo: 'C0219',
            parentId: 'C02',
          },
          {
            id: 'C0220',
            name: 'CHEFA ROBIT',
            sortNo: 'C0220',
            parentId: 'C02',
          },
          {
            id: 'C0221',
            name: 'HARBU',
            sortNo: 'C0221',
            parentId: 'C02',
          },
          {
            id: 'C0222',
            name: 'JAMMA',
            sortNo: 'C0222',
            parentId: 'C02',
          },
          {
            id: 'C0223',
            name: 'MASHA',
            sortNo: 'C0223',
            parentId: 'C02',
          },
          {
            id: 'C0224',
            name: 'SAINT',
            sortNo: 'C0224',
            parentId: 'C02',
          },
          {
            id: 'C0225',
            name: 'MEKOY',
            sortNo: 'C0225',
            parentId: 'C02',
          },
          {
            id: 'C0226',
            name: 'DESSIE CSC 3',
            sortNo: 'C0226',
            parentId: 'C02',
          },
          {
            id: 'C0227',
            name: 'WOIN AMBA',
            sortNo: 'C0227',
            parentId: 'C02',
          },
        ],
      },
      {
        id: 'C03',
        name: 'Gonder District',
        sortNo: 'C03',
        parentId: 'C',
        children: [
          {
            id: 'C031',
            name: 'GONDER 1',
            sortNo: 'C031',
            parentId: 'C03',
          },
          {
            id: 'C032',
            name: 'GONDER 2',
            sortNo: 'C032',
            parentId: 'C03',
          },
          {
            id: 'C033',
            name: 'GONDER   NO.3',
            sortNo: 'C033',
            parentId: 'C03',
          },
          {
            id: 'C034',
            name: 'DABAT',
            sortNo: 'C034',
            parentId: 'C03',
          },
          {
            id: 'C035',
            name: 'DEBARK',
            sortNo: 'C035',
            parentId: 'C03',
          },
          {
            id: 'C036',
            name: 'KOLLADIBA',
            sortNo: 'C036',
            parentId: 'C03',
          },
          {
            id: 'C037',
            name: 'METEMA',
            sortNo: 'C037',
            parentId: 'C03',
          },
          {
            id: 'C038',
            name: 'SANJA',
            sortNo: 'C038',
            parentId: 'C03',
          },
          {
            id: 'C039',
            name: 'MAKSEGNET',
            sortNo: 'C039',
            parentId: 'C03',
          },
          {
            id: 'C0310',
            name: 'DELI',
            sortNo: 'C0310',
            parentId: 'C03',
          },
          {
            id: 'C0311',
            name: 'AREBAYA',
            sortNo: 'C0311',
            parentId: 'C03',
          },
          {
            id: 'C0312',
            name: 'GELAJO',
            sortNo: 'C0312',
            parentId: 'C03',
          },
          {
            id: 'C0313',
            name: 'GUHASSA',
            sortNo: 'C0313',
            parentId: 'C03',
          },
          {
            id: 'C0314',
            name: 'MEKANE BIRHAN',
            sortNo: 'C0314',
            parentId: 'C03',
          },

          {
            id: 'C0315',
            name: 'SHAWERA',
            sortNo: 'C0315',
            parentId: 'C03',
          },
          {
            id: 'C0316',
            name: 'TEKELDINGAY',
            sortNo: 'C0316',
            parentId: 'C03',
          },
          {
            id: 'C0317',
            name: 'AMBA GIORGIS',
            sortNo: 'C0317',
            parentId: 'C03',
          },
          {
            id: 'C0318',
            name: 'METEMA YOHANS',
            sortNo: 'C0318',
            parentId: 'C03',
          },
          {
            id: 'C0319',
            name: 'CHILGA',
            sortNo: 'C0319',
            parentId: 'C03',
          },
          {
            id: 'C0320',
            name: 'ADARIKAYE',
            sortNo: 'C0320',
            parentId: 'C03',
          },
          {
            id: 'C0321',
            name: 'ABIDRAFI',
            sortNo: 'C0321',
            parentId: 'C03',
          },
          {
            id: 'C0322',
            name: 'CHUAHIT',
            sortNo: 'C0322',
            parentId: 'C03',
          },
          {
            id: 'C0323',
            name: 'KIRAKIR',
            sortNo: 'C0323',
            parentId: 'C03',
          },
        ],
      },
      {
        id: 'C04',
        name: 'Debre Birhan District',
        sortNo: 'C04',
        parentId: 'C',
        children: [
          {
            id: 'C041',
            name: 'DEBRE BIRHAN NO 1',
            sortNo: 'C041',
            parentId: 'C04',
          },
          {
            id: 'C042',
            name: 'DEBRE BIRHAN NO 2',
            sortNo: 'C042',
            parentId: 'C04',
          },
          {
            id: 'C043',
            name: 'ENEWARI',
            sortNo: 'C043',
            parentId: 'C04',
          },
          {
            id: 'C044',
            name: 'ANKOBER',
            sortNo: 'C044',
            parentId: 'C04',
          },
          {
            id: 'C045',
            name: 'ALEMKETEMA',
            sortNo: 'C045',
            parentId: 'C04',
          },
          {
            id: 'C046',
            name: 'LEMI',
            sortNo: 'C046',
            parentId: 'C04',
          },
          {
            id: 'C047',
            name: 'HAGEREMARIAM',
            sortNo: 'C047',
            parentId: 'C04',
          },
          {
            id: 'C048',
            name: 'ARERTI',
            sortNo: 'C048',
            parentId: 'C04',
          },
          {
            id: 'C049',
            name: 'DEBRESINA',
            sortNo: 'C049',
            parentId: 'C04',
          },
          {
            id: 'C0410',
            name: 'MEHALMEDA',
            sortNo: 'C0410',
            parentId: 'C04',
          },
          {
            id: 'C0411',
            name: 'MOLALLE',
            sortNo: 'C0411',
            parentId: 'C04',
          },
          {
            id: 'C0412',
            name: 'SHOAROBIT',
            sortNo: 'C0412',
            parentId: 'C04',
          },

          {
            id: 'C0413',
            name: 'GISHERABL',
            sortNo: 'C0413',
            parentId: 'C04',
          },
          {
            id: 'C0414',
            name: 'METIHIBILA',
            sortNo: 'C0414',
            parentId: 'C04',
          },

          {
            id: 'C0415',
            name: 'SELADINGAY',
            sortNo: 'C0415',
            parentId: 'C04',
          },
          {
            id: 'C0416',
            name: 'GINAGER',
            sortNo: 'C0416',
            parentId: 'C04',
          },
          {
            id: 'C0417',
            name: 'DENBA',
            sortNo: 'C0417',
            parentId: 'C04',
          },
          {
            id: 'C0418',
            name: 'CHACHA',
            sortNo: 'C0418',
            parentId: 'C04',
          },
          {
            id: 'C0419',
            name: 'ATAYE',
            sortNo: 'C0419',
            parentId: 'C04',
          },
          {
            id: 'C0420',
            name: 'MIDA',
            sortNo: 'C0420',
            parentId: 'C04',
          },
        ],
      },

      {
        id: 'C05',
        name: 'Debre Markos District',
        sortNo: 'C05',
        parentId: 'C',
        children: [
          {
            id: 'C051',
            name: 'DEBREMARIKOS NO 1',
            sortNo: 'C051',
            parentId: 'C05',
          },
          {
            id: 'C052',
            name: 'DEBREMARIKOS NO 2',
            sortNo: 'C052',
            parentId: 'C05',
          },
          {
            id: 'C053',
            name: 'AMANUEL',
            sortNo: 'C053',
            parentId: 'C05',
          },
          {
            id: 'C054',
            name: 'BICHENA',
            sortNo: 'C054',
            parentId: 'C05',
          },
          {
            id: 'C055',
            name: 'DEJEN',
            sortNo: 'C055',
            parentId: 'C05',
          },
          {
            id: 'C056',
            name: 'GINDEWOYIN',
            sortNo: 'C056',
            parentId: 'C05',
          },
          {
            id: 'C057',
            name: 'KUYE',
            sortNo: 'C057',
            parentId: 'C05',
          },
          {
            id: 'C058',
            name: 'MOTA',
            sortNo: 'C058',
            parentId: 'C05',
          },
          {
            id: 'C059',
            name: 'DIGOTSION',
            sortNo: 'C059',
            parentId: 'C05',
          },
          {
            id: 'C0510',
            name: 'LUMAMME',
            sortNo: 'C0510',
            parentId: 'C05',
          },
          {
            id: 'C0511',
            name: 'MERTOLEMARIAM',
            sortNo: 'C0511',
            parentId: 'C05',
          },
          {
            id: 'C0512',
            name: 'YEJUBE',
            sortNo: 'C0512',
            parentId: 'C05',
          },

          {
            id: 'C0513',
            name: 'BURIE',
            sortNo: 'C0513',
            parentId: 'C05',
          },
          {
            id: 'C0514',
            name: 'F / SELAM',
            sortNo: 'C0514',
            parentId: 'C05',
          },
          {
            id: 'C0515',
            name: 'SHENDI',
            sortNo: 'C0515',
            parentId: 'C05',
          },
          {
            id: 'C0516',
            name: 'DENBECHA',
            sortNo: 'C0516',
            parentId: 'C05',
          },
          {
            id: 'C0517',
            name: 'FERES BET',
            sortNo: 'C0517',
            parentId: 'C05',
          },
          {
            id: 'C0518',
            name: 'DEBREELIAS',
            sortNo: 'C0518',
            parentId: 'C05',
          },
          {
            id: 'C0519',
            name: 'GEBEZEMARIAM',
            sortNo: 'C0519',
            parentId: 'C05',
          },
          {
            id: 'C0520',
            name: 'YEDUHA',
            sortNo: 'C0520',
            parentId: 'C05',
          },
        ],
      },
      {
        id: 'C06',
        name: 'Wolidia District',
        sortNo: 'C06',
        parentId: 'C',
        children: [
          {
            id: 'C061',
            name: 'WOLEDIA',
            sortNo: 'C061',
            parentId: 'C06',
          },
          {
            id: 'C062',
            name: 'GASHENA',
            sortNo: 'C062',
            parentId: 'C06',
          },
          {
            id: 'C063',
            name: 'MERSA',
            sortNo: 'C063',
            parentId: 'C06',
          },
          {
            id: 'C064',
            name: 'DAWENT',
            sortNo: 'C064',
            parentId: 'C06',
          },
          {
            id: 'C065',
            name: 'FILAQIT',
            sortNo: 'C065',
            parentId: 'C06',
          },
          {
            id: 'C066',
            name: 'AMEDEWORK',
            sortNo: 'C066',
            parentId: 'C06',
          },
          {
            id: 'C067',
            name: 'LALIBELA',
            sortNo: 'C067',
            parentId: 'C06',
          },
          {
            id: 'C068',
            name: 'KOBO',
            sortNo: 'C068',
            parentId: 'C06',
          },
          {
            id: 'C069',
            name: 'SEKOTA',
            sortNo: 'C069',
            parentId: 'C06',
          },
          {
            id: 'C0610',
            name: 'NUBAK',
            sortNo: 'C0610',
            parentId: 'C06',
          },

          {
            id: 'C0611',
            name: 'AYENABUGUNA',
            sortNo: 'C0611',
            parentId: 'C06',
          },
          {
            id: 'C0612',
            name: 'ZEQUALA',
            sortNo: 'C0612',
            parentId: 'C06',
          },
          {
            id: 'C0613',
            name: 'ROBIT',
            sortNo: 'C0613',
            parentId: 'C06',
          },
          {
            id: 'C0614',
            name: 'WOLDIA CSC2',
            sortNo: 'C0614',
            parentId: 'C06',
          },
          {
            id: 'C0615',
            name: 'MUJA',
            sortNo: 'C0615',
            parentId: 'C06',
          },
        ],
      },
    ],
  },

  {
    id: 'D',
    name: 'SNNPR',
    sortNo: 'D',
    parentId: '0',
    children: [
      {
        id: 'D01',
        name: 'Hosaena District',
        sortNo: 'D01',
        parentId: 'D',
        children: [
          {
            id: 'D011',
            name: 'HOSSHENA',
            sortNo: 'D011',
            parentId: 'D01',
          },
          {
            id: 'D012',
            name: 'WELKITE',
            sortNo: 'D012',
            parentId: 'D01',
          },
          {
            id: 'D013',
            name: 'BUTAJIRA',
            sortNo: 'D013',
            parentId: 'D01',
          },
          {
            id: 'D014',
            name: 'WERABE',
            sortNo: 'D014',
            parentId: 'D01',
          },
          {
            id: 'D015',
            name: 'BUEE',
            sortNo: 'D015',
            parentId: 'D01',
          },
          {
            id: 'D016',
            name: 'ENDIBER',
            sortNo: 'D016',
            parentId: 'D01',
          },
          {
            id: 'D017',
            name: 'GINCHIRE',
            sortNo: 'D017',
            parentId: 'D01',
          },
          {
            id: 'D018',
            name: 'AGENA',
            sortNo: 'D018',
            parentId: 'D01',
          },
          {
            id: 'D019',
            name: 'DARGAYE',
            sortNo: 'D019',
            parentId: 'D01',
          },
          {
            id: 'D0110',
            name: 'DAOCHA',
            sortNo: 'D0110',
            parentId: 'D01',
          },
          {
            id: 'D0111',
            name: 'TORA',
            sortNo: 'D0111',
            parentId: 'D01',
          },
          {
            id: 'D0112',
            name: 'DURAME',
            sortNo: 'D0112',
            parentId: 'D01',
          },

          {
            id: 'D0113',
            name: 'GIMBICHU',
            sortNo: 'D0113',
            parentId: 'D01',
          },
          {
            id: 'D0114',
            name: 'MUDULA',
            sortNo: 'D0114',
            parentId: 'D01',
          },
          {
            id: 'D0115',
            name: 'DOYOGENA',
            sortNo: 'D0115',
            parentId: 'D01',
          },
          {
            id: 'D0116',
            name: 'ANGACHA',
            sortNo: 'D0116',
            parentId: 'D01',
          },
          {
            id: 'D0117',
            name: 'LERA',
            sortNo: 'D0117',
            parentId: 'D01',
          },
          {
            id: 'D0118',
            name: 'MORSITO',
            sortNo: 'D0118',
            parentId: 'D01',
          },
          {
            id: 'D0119',
            name: 'SHINSICHO',
            sortNo: 'D0119',
            parentId: 'D01',
          },
          {
            id: 'D0120',
            name: 'HOSSANA NO 2',
            sortNo: 'D0120',
            parentId: 'D01',
          },
          {
            id: 'D0121',
            name: 'HAWARIAT',
            sortNo: 'D0121',
            parentId: 'D01',
          },
          {
            id: 'D0122',
            name: 'GOMBORA',
            sortNo: 'D0122',
            parentId: 'D01',
          },
          {
            id: 'D0123',
            name: 'AREKIT',
            sortNo: 'D0123',
            parentId: 'D01',
          },
          {
            id: 'D0124',
            name: 'FONKE',
            sortNo: 'D0124',
            parentId: 'D01',
          },
          {
            id: 'D0125',
            name: 'DINQULA',
            sortNo: 'D0125',
            parentId: 'D01',
          },
          {
            id: 'D0126',
            name: 'KOSHE',
            sortNo: 'D0126',
            parentId: 'D01',
          },
        ],
      },
      {
        id: 'D02',
        name: 'Wolita District',
        sortNo: 'D02',
        parentId: 'D',
        children: [
          {
            id: 'D021',
            name: 'WELAYITA SODO NO 1',
            sortNo: 'D021',
            parentId: 'D02',
          },
          {
            id: 'D022',
            name: 'WELAYITA SODO NO 2',
            sortNo: 'D022',
            parentId: 'D02',
          },
          {
            id: 'D023',
            name: 'BELE(GUNINI)',
            sortNo: 'D023',
            parentId: 'D02',
          },
          {
            id: 'D024',
            name: 'BODITI',
            sortNo: 'D024',
            parentId: 'D02',
          },
          {
            id: 'D025',
            name: 'GESUPAN',
            sortNo: 'D025',
            parentId: 'D02',
          },
          {
            id: 'D026',
            name: 'HADERO',
            sortNo: 'D026',
            parentId: 'D02',
          },
          {
            id: 'D027',
            name: 'HUMBO',
            sortNo: 'D027',
            parentId: 'D02',
          },
          {
            id: 'D028',
            name: 'SHONE',
            sortNo: 'D028',
            parentId: 'D02',
          },
          {
            id: 'D029',
            name: 'ALABA',
            sortNo: 'D029',
            parentId: 'D02',
          },
          {
            id: 'D0210',
            name: 'BULE',
            sortNo: 'D0210',
            parentId: 'D02',
          },

          {
            id: 'D0211',
            name: 'WENAGO',
            sortNo: 'D0211',
            parentId: 'D02',
          },
          {
            id: 'D0212',
            name: 'YIRGACHEFE',
            sortNo: 'D0212',
            parentId: 'D02',
          },
          {
            id: 'D0213',
            name: 'DILLA',
            sortNo: 'D0213',
            parentId: 'D02',
          },
          {
            id: 'D0214',
            name: 'CHELELEKTU',
            sortNo: 'D0214',
            parentId: 'D02',
          },
          {
            id: 'D0215',
            name: 'AMAROKELE',
            sortNo: 'D0215',
            parentId: 'D02',
          },
          {
            id: 'D0216',
            name: 'BOREDA',
            sortNo: 'D0216',
            parentId: 'D02',
          },
        ],
      },
      {
        id: 'D03',
        name: 'Arbaminch District',
        sortNo: 'D03',
        parentId: 'D',
        children: [
          {
            id: 'D031',
            name: 'ARBAMINCH NO 1',
            sortNo: 'D031',
            parentId: 'D03',
          },
          {
            id: 'D032',
            name: 'ARBAMINCH NO 2',
            sortNo: 'D032',
            parentId: 'D03',
          },
          {
            id: 'D033',
            name: 'SAWELA',
            sortNo: 'D033',
            parentId: 'D03',
          },
          {
            id: 'D034',
            name: 'CHENCHA',
            sortNo: 'D034',
            parentId: 'D03',
          },
          {
            id: 'D035',
            name: 'GRESE / BONKE',
            sortNo: 'D035',
            parentId: 'D03',
          },
          {
            id: 'D036',
            name: 'BASKITO',
            sortNo: 'D036',
            parentId: 'D03',
          },
          {
            id: 'D037',
            name: 'SEGEN',
            sortNo: 'D037',
            parentId: 'D03',
          },
          {
            id: 'D038',
            name: 'JINKA',
            sortNo: 'D038',
            parentId: 'D03',
          },
          {
            id: 'D039',
            name: 'DIMEKA',
            sortNo: 'D039',
            parentId: 'D03',
          },
          {
            id: 'D0310',
            name: 'MIERABABAY',
            sortNo: 'D0310',
            parentId: 'D03',
          },
          {
            id: 'D0311',
            name: 'BETO',
            sortNo: 'D0311',
            parentId: 'D03',
          },
          {
            id: 'D0312',
            name: 'GIDOLE / DERASHE',
            sortNo: 'D0312',
            parentId: 'D03',
          },
          {
            id: 'D0313',
            name: 'SELAMBER',
            sortNo: 'D0313',
            parentId: 'D03',
          },
          {
            id: 'D0314',
            name: 'KONSSO',
            sortNo: 'D0314',
            parentId: 'D03',
          },

          {
            id: 'D0315',
            name: 'BURJI',
            sortNo: 'D0315',
            parentId: 'D03',
          },
          {
            id: 'D0316',
            name: 'GEDEB',
            sortNo: 'D0316',
            parentId: 'D03',
          },
          {
            id: 'D0317',
            name: 'KENBA',
            sortNo: 'D0317',
            parentId: 'D03',
          },
          {
            id: 'D0318',
            name: 'DITA',
            sortNo: 'D0318',
            parentId: 'D03',
          },
        ],
      },
      {
        id: 'D04',
        name: 'Hawasa District',
        sortNo: 'D04',
        parentId: 'D',
        children: [
          {
            id: 'D041',
            name: 'HAWASSA NO 1',
            sortNo: 'D041',
            parentId: 'D04',
          },
          {
            id: 'D042',
            name: 'HAWASSA NO 2',
            sortNo: 'D042',
            parentId: 'D04',
          },
          {
            id: 'D043',
            name: 'HAWASSA NO 3',
            sortNo: 'D043',
            parentId: 'D04',
          },
          {
            id: 'D044',
            name: 'HAWASSA NO 4',
            sortNo: 'D044',
            parentId: 'D04',
          },
          {
            id: 'D045',
            name: 'ALETA WONDO',
            sortNo: 'D045',
            parentId: 'D04',
          },
          {
            id: 'D046',
            name: 'DAYE',
            sortNo: 'D046',
            parentId: 'D04',
          },
          {
            id: 'D047',
            name: 'H / SELAME',
            sortNo: 'D047',
            parentId: 'D04',
          },
          {
            id: 'D048',
            name: 'YIRGALEME',
            sortNo: 'D048',
            parentId: 'D04',
          },
          {
            id: 'D049',
            name: 'YIRBA',
            sortNo: 'D049',
            parentId: 'D04',
          },
          {
            id: 'D0410',
            name: 'SHEBEDINOLAKU',
            sortNo: 'D0410',
            parentId: 'D04',
          },
          {
            id: 'D0411',
            name: 'ARBEONA',
            sortNo: 'D0411',
            parentId: 'D04',
          },
          {
            id: 'D0412',
            name: 'CHUKO',
            sortNo: 'D0412',
            parentId: 'D04',
          },
          {
            id: 'D0410',
            name: 'GIRJA',
            sortNo: 'D0410',
            parentId: 'D04',
          },
          {
            id: 'D0411',
            name: 'KEBADO',
            sortNo: 'D0411',
            parentId: 'D04',
          },
          {
            id: 'D0412',
            name: 'WENDOGENET',
            sortNo: 'D0412',
            parentId: 'D04',
          },
        ],
      },
    ],
  },

  {
    id: 'E',
    name: 'Somalia',
    sortNo: 'E',
    parentId: '0',
    children: [
      {
        id: 'E01',
        name: 'Gode District',
        sortNo: 'E01',
        parentId: 'E',
        children: [
          {
            id: 'E011',
            name: 'GODE BR',
            sortNo: 'E011',
            parentId: 'E01',
          },
          {
            id: 'E012',
            name: 'DOLOODO',
            sortNo: 'E012',
            parentId: 'E01',
          },
          {
            id: 'E013',
            name: 'HARGELE',
            sortNo: 'E013',
            parentId: 'E01',
          },
          {
            id: 'E014',
            name: 'SHILABO',
            sortNo: 'E014',
            parentId: 'E01',
          },
          {
            id: 'E015',
            name: 'GASHAMO',
            sortNo: 'E015',
            parentId: 'E01',
          },
          {
            id: 'E016',
            name: 'BOHE',
            sortNo: 'E016',
            parentId: 'E01',
          },
          {
            id: 'E017',
            name: 'WARDER',
            sortNo: 'E017',
            parentId: 'E01',
          },
          {
            id: 'E018',
            name: 'KEBRIDEHAR',
            sortNo: 'E018',
            parentId: 'E01',
          },
          {
            id: 'E019',
            name: 'DENEN',
            sortNo: 'E019',
            parentId: 'E01',
          },
          {
            id: 'E0110',
            name: 'EMI',
            sortNo: 'E0110',
            parentId: 'E01',
          },
          {
            id: 'E0111',
            name: 'FILETU',
            sortNo: 'E0111',
            parentId: 'E01',
          },
          {
            id: 'E0112',
            name: 'KELAFO',
            sortNo: 'E0112',
            parentId: 'E01',
          },

          {
            id: 'E0113',
            name: 'FERFER',
            sortNo: 'E0113',
            parentId: 'E01',
          },
        ],
      },
      {
        id: 'E02',
        name: 'Jigjiga District',
        sortNo: 'E02',
        parentId: 'E',
        children: [
          {
            id: 'E021',
            name: 'AYESHA',
            sortNo: 'E021',
            parentId: 'E02',
          },
          {
            id: 'E022',
            name: 'ERER',
            sortNo: 'E022',
            parentId: 'E02',
          },
          {
            id: 'E023',
            name: 'KULEN',
            sortNo: 'E023',
            parentId: 'E02',
          },
          {
            id: 'E024',
            name: 'AWARE',
            sortNo: 'E024',
            parentId: 'E02',
          },
          {
            id: 'E025',
            name: 'SHEKOSHI',
            sortNo: 'E025',
            parentId: 'E02',
          },
          {
            id: 'E026',
            name: 'FIKE',
            sortNo: 'E026',
            parentId: 'E02',
          },
          {
            id: 'E027',
            name: 'AWBERE',
            sortNo: 'E027',
            parentId: 'E02',
          },
          {
            id: 'E028',
            name: 'KEBRIBEYAHI',
            sortNo: 'E028',
            parentId: 'E02',
          },
          {
            id: 'E029',
            name: 'DEGEHABUR',
            sortNo: 'E029',
            parentId: 'E02',
          },
          {
            id: 'E0210',
            name: 'JIJIGA NO 1',
            sortNo: 'E0210',
            parentId: 'E02',
          },

          {
            id: 'E0211',
            name: 'JIJIGA NO 2',
            sortNo: 'E0211',
            parentId: 'E02',
          },
          {
            id: 'E0212',
            name: 'FAFEN',
            sortNo: 'E0212',
            parentId: 'E02',
          },
          {
            id: 'E0213',
            name: 'TOGOWUCHALE',
            sortNo: 'E0213',
            parentId: 'E02',
          },
        ],
      },
    ],
  },

  {
    id: 'F',
    name: 'Tigray',
    sortNo: 'F',
    parentId: '0',
    children: [
      {
        id: 'F01',
        name: 'Mekele District',
        sortNo: 'F01',
        parentId: 'F',
        children: [
          {
            id: 'F011',
            name: 'WUKRO',
            sortNo: 'F011',
            parentId: 'F01',
          },
          {
            id: 'F012',
            name: 'DEWHAN',
            sortNo: 'F012',
            parentId: 'F01',
          },
          {
            id: 'F013',
            name: 'TIMUGA/WAJA',
            sortNo: 'F013',
            parentId: 'F01',
          },
          {
            id: 'F014',
            name: 'BIZET',
            sortNo: 'F014',
            parentId: 'F01',
          },
          {
            id: 'F015',
            name: 'FIREWEYNI',
            sortNo: 'F015',
            parentId: 'F01',
          },
          {
            id: 'F016',
            name: 'YECHILA',
            sortNo: 'F016',
            parentId: 'F01',
          },
          {
            id: 'F017',
            name: 'HAWZEN',
            sortNo: 'F017',
            parentId: 'F01',
          },
          {
            id: 'F018',
            name: 'ADISHEHUATSIBI',
            sortNo: 'F018',
            parentId: 'F01',
          },
          {
            id: 'F019',
            name: 'HAGERE SELAM',
            sortNo: 'F019',
            parentId: 'F01',
          },
          {
            id: 'F0110',
            name: 'EDGA HAMUS',
            sortNo: 'F0110',
            parentId: 'F01',
          },
          {
            id: 'F0111',
            name: 'MEHONI',
            sortNo: 'F0111',
            parentId: 'F01',
          },
          {
            id: 'F0112',
            name: 'SAMRE',
            sortNo: 'F0112',
            parentId: 'F01',
          },
          {
            id: 'F0113',
            name: 'ZALANBESA',
            sortNo: 'F0113',
            parentId: 'F01',
          },
          {
            id: 'F0114',
            name: 'KOREM',
            sortNo: 'F0114',
            parentId: 'F01',
          },
          {
            id: 'F0115',
            name: 'ADIGUDEM',
            sortNo: 'F0115',
            parentId: 'F01',
          },
          {
            id: 'F0116',
            name: 'ABI ADI',
            sortNo: 'F0116',
            parentId: 'F01',
          },
          {
            id: 'F0117',
            name: 'MAYCHEW',
            sortNo: 'F0117',
            parentId: 'F01',
          },
          {
            id: 'F0118',
            name: 'KUIHA',
            sortNo: 'F0118',
            parentId: 'F01',
          },
          {
            id: 'F0119',
            name: 'ALAMATA',
            sortNo: 'F0119',
            parentId: 'F01',
          },
          {
            id: 'F0120',
            name: 'MEKELLE S.C - 2',
            sortNo: 'F0120',
            parentId: 'F01',
          },
          {
            id: 'F0121',
            name: 'ADIRAT',
            sortNo: 'F0121',
            parentId: 'F01',
          },
          {
            id: 'F0122',
            name: 'MEKELLE S.C - 1',
            sortNo: 'F0122',
            parentId: 'F01',
          },
          {
            id: 'F0123',
            name: 'MEKELLE S.C - 4(INDUSTRY PARK)',
            sortNo: 'F0123',
            parentId: 'F01',
          },
          {
            id: 'F0124',
            name: 'AGULAE',
            sortNo: 'F0124',
            parentId: 'F01',
          },
        ],
      },
      {
        id: 'F02',
        name: 'Shere District',
        sortNo: 'F02',
        parentId: 'F',
        children: [
          {
            id: 'F021',
            name: 'MYHANSEY',
            sortNo: 'F021',
            parentId: 'F02',
          },
          {
            id: 'F022',
            name: 'SHIRARO',
            sortNo: 'F022',
            parentId: 'F02',
          },
          {
            id: 'F023',
            name: 'HUMERA',
            sortNo: 'F023',
            parentId: 'F02',
          },
          {
            id: 'F024',
            name: 'DANSHA',
            sortNo: 'F024',
            parentId: 'F02',
          },
          {
            id: 'F025',
            name: 'SEMEMA',
            sortNo: 'F025',
            parentId: 'F02',
          },
          {
            id: 'F026',
            name: 'ADIDAERO',
            sortNo: 'F026',
            parentId: 'F02',
          },
          {
            id: 'F027',
            name: 'NEBELET',
            sortNo: 'F027',
            parentId: 'F02',
          },
          {
            id: 'F028',
            name: 'MAY STEBRI',
            sortNo: 'F028',
            parentId: 'F02',
          },
          {
            id: 'F029',
            name: 'SELEKLEKA',
            sortNo: 'F029',
            parentId: 'F02',
          },
          {
            id: 'F0210',
            name: 'ENDABA GUNA',
            sortNo: 'F0210',
            parentId: 'F02',
          },

          {
            id: 'F0211',
            name: 'WUKRO MARAY',
            sortNo: 'F0211',
            parentId: 'F02',
          },
          {
            id: 'F0212',
            name: 'RAMA',
            sortNo: 'F0212',
            parentId: 'F02',
          },
          {
            id: 'F0213',
            name: 'ADEGA ARBI',
            sortNo: 'F0213',
            parentId: 'F02',
          },
          {
            id: 'F0214',
            name: 'BAEKER INDUSTRY PARK',
            sortNo: 'F0214',
            parentId: 'F02',
          },
          {
            id: 'F0215',
            name: 'ENTICHO',
            sortNo: 'F0215',
            parentId: 'F02',
          },
          {
            id: 'F0216',
            name: 'ADWA',
            sortNo: 'F0216',
            parentId: 'F02',
          },
          {
            id: 'F0217',
            name: 'SHIRE',
            sortNo: 'F0217',
            parentId: 'F02',
          },
          {
            id: 'F0218',
            name: 'AXUM',
            sortNo: 'F0218',
            parentId: 'F02',
          },
          {
            id: 'F0219',
            name: 'ADI REMETS',
            sortNo: 'F0219',
            parentId: 'F02',
          },
          {
            id: 'F0220',
            name: 'MAY GABA',
            sortNo: 'F0220',
            parentId: 'F02',
          },
          {
            id: 'F0221',
            name: 'ADI HAGERAY',
            sortNo: 'F0221',
            parentId: 'F02',
          },
        ],
      },
    ],
  },

  {
    id: 'G',
    name: 'Afar Region',
    sortNo: 'G',
    parentId: '0',
    children: [
      {
        id: 'G01',
        name: 'SEMERA CSC',
        sortNo: 'G01',
        parentId: 'G',
      },
      {
        id: 'G02',
        name: 'MELKA WERER',
        sortNo: 'G02',
        parentId: 'G',
      },
      {
        id: 'G03',
        name: 'AWASH 7 KILLO',
        sortNo: 'G03',
        parentId: 'G',
      },
      {
        id: 'G04',
        name: 'TELALAK',
        sortNo: 'G04',
        parentId: 'G',
      },
      {
        id: 'G05',
        name: 'GEWANE',
        sortNo: 'G05',
        parentId: 'G',
      },
      {
        id: 'G06',
        name: 'DECHETO',
        sortNo: 'G06',
        parentId: 'G',
      },
      {
        id: 'G07',
        name: 'LOGIA',
        sortNo: 'G07',
        parentId: 'G',
      },
      {
        id: 'G08',
        name: 'ASAYTA',
        sortNo: 'G08',
        parentId: 'G',
      },
      {
        id: 'G09',
        name: 'DUBTI',
        sortNo: 'G09',
        parentId: 'G',
      },
      {
        id: 'G010',
        name: 'MILE',
        sortNo: 'G010',
        parentId: 'G',
      },
      {
        id: 'G011',
        name: 'AFDERA',
        sortNo: 'G011',
        parentId: 'G',
      },
      {
        id: 'G012',
        name: 'ELWEHA',
        sortNo: 'G012',
        parentId: 'G',
      },
      {
        id: 'G013',
        name: 'Shiket / Abala',
        sortNo: 'G013',
        parentId: 'G',
      },
      {
        id: 'G014',
        name: 'BRHALE',
        sortNo: 'G014',
        parentId: 'G',
      },
      {
        id: 'G015',
        name: 'CHIFRA',
        sortNo: 'G015',
        parentId: 'G',
      },
      {
        id: 'G016',
        name: 'SUNUTA',
        sortNo: 'G016',
        parentId: 'G',
      },
      {
        id: 'G017',
        name: 'KELEWAN',
        sortNo: 'G017',
        parentId: 'G',
      },
      {
        id: 'G018',
        name: 'KUNEBA CSC',
        sortNo: 'G018',
        parentId: 'G',
      },
    ],
  },

  {
    id: 'H',
    name: 'DIRE DAWA',
    sortNo: 'H',
    parentId: '0',
    children: [
      {
        id: 'H01',
        name: 'DIRE DAWA NO 1',
        sortNo: 'H01',
        parentId: 'H',
      },
      {
        id: 'H02',
        name: 'DIRE DAWA NO 2',
        sortNo: 'H02',
        parentId: 'H',
      },
      {
        id: 'H03',
        name: 'DIRE MELKA',
        sortNo: 'H03',
        parentId: 'H',
      },
      {
        id: 'H04',
        name: 'GENET MENAFESHA',
        sortNo: 'H04',
        parentId: 'H',
      },
      {
        id: 'H05',
        name: 'DIRE DAWA NO 5(Industry Park)',
        sortNo: 'H05',
        parentId: 'H',
      },
    ],
  },

  {
    id: 'I',
    name: 'HARER Region',
    sortNo: 'I',
    parentId: '0',
    children: [
      {
        id: 'I01',
        name: 'HARER NO 1',
        sortNo: 'I01',
        parentId: 'I',
      },
      {
        id: 'I02',
        name: 'HARER NO 2',
        sortNo: 'I02',
        parentId: 'I',
      },
      {
        id: 'I03',
        name: 'DERE TEYARA',
        sortNo: 'I03',
        parentId: 'I',
      },
      {
        id: 'I04',
        name: 'EARER WELDEYA',
        sortNo: 'I04',
        parentId: 'I',
      },
      {
        id: 'I05',
        name: 'SOFI',
        sortNo: 'I05',
        parentId: 'I',
      },
    ],
  },

  {
    id: 'J',
    name: 'South West Region',
    sortNo: 'J',
    parentId: '0',
    children: [
      {
        id: 'J01',
        name: 'GESA',
        sortNo: 'J01',
        parentId: 'J',
      },
      {
        id: 'J02',
        name: 'TERCHA',
        sortNo: 'J02',
        parentId: 'J',
      },
      {
        id: 'J03',
        name: 'TOCHA',
        sortNo: 'J03',
        parentId: 'J',
      },
      {
        id: 'J04',
        name: 'BONGA',
        sortNo: 'J04',
        parentId: 'J',
      },
      {
        id: 'J05',
        name: 'MASHA',
        sortNo: 'J05',
        parentId: 'J',
      },
      {
        id: 'J06',
        name: 'MIZAN',
        sortNo: 'J06',
        parentId: 'J',
      },
      {
        id: 'J07',
        name: 'TEPPI',
        sortNo: 'J07',
        parentId: 'J',
      },
      {
        id: 'J08',
        name: 'DAKA',
        sortNo: 'J08',
        parentId: 'J',
      },
      {
        id: 'J09',
        name: 'ODA',
        sortNo: 'J09',
        parentId: 'J',
      },
      {
        id: 'J010',
        name: 'CHENA',
        sortNo: 'J010',
        parentId: 'J',
      },
      {
        id: 'J011',
        name: 'BIFTU',
        sortNo: 'J011',
        parentId: 'J',
      },
      {
        id: 'J012',
        name: 'DEBRE WORK',
        sortNo: 'J012',
        parentId: 'J',
      },
      {
        id: 'J013',
        name: 'SHEBENCH',
        sortNo: 'J013',
        parentId: 'J',
      },
      {
        id: 'J014',
        name: 'AMEYA-KONTA',
        sortNo: 'J014',
        parentId: 'J',
      },
      {
        id: 'J015',
        name: 'CHIRI',
        sortNo: 'J015',
        parentId: 'J',
      },
      {
        id: 'J016',
        name: 'ADIYOKAKA',
        sortNo: 'J016',
        parentId: 'J',
      },
      {
        id: 'J017',
        name: 'GIMBO',
        sortNo: 'J017',
        parentId: 'J',
      },
      {
        id: 'J018',
        name: 'JEMU',
        sortNo: 'J018',
        parentId: 'J',
      },
    ],
  },
  {
    id: 'M',
    name: 'Benishangul-Gumuz Region',
    sortNo: 'M',
    parentId: '0',
    children: [
      {
        id: 'M01',
        name: 'Assosa District',
        sortNo: 'M01',
        parentId: 'M',
        children: [
          {
            id: 'M011',
            name: 'ASOSSA',
            sortNo: 'M011',
            parentId: 'M01',
          },
          {
            id: 'M012',
            name: 'MENEGE',
            sortNo: 'M012',
            parentId: 'M01',
          },
          {
            id: 'M013',
            name: 'BAMBASI',
            sortNo: 'M013',
            parentId: 'M01',
          },
          {
            id: 'M014',
            name: 'KUMIRUK',
            sortNo: 'M014',
            parentId: 'M01',
          },
          {
            id: 'M015',
            name: 'PAWI',
            sortNo: 'M015',
            parentId: 'M01',
          },
          {
            id: 'M016',
            name: 'SOGE',
            sortNo: 'M016',
            parentId: 'M01',
          },
          {
            id: 'M017',
            name: 'DEBRESEYIT',
            sortNo: 'M017',
            parentId: 'M01',
          },
          {
            id: 'M018',
            name: 'MANKUSH',
            sortNo: 'M018',
            parentId: 'M01',
          },
          {
            id: 'M019',
            name: 'BULLEN',
            sortNo: 'M019',
            parentId: 'M01',
          },
          {
            id: 'M0110',
            name: 'ODDA BILENDIGELU',
            sortNo: 'M0110',
            parentId: 'M01',
          },
          {
            id: 'M0111',
            name: 'TONGO',
            sortNo: 'M0111',
            parentId: 'M01',
          },
          {
            id: 'M0112',
            name: 'KAMASHI',
            sortNo: 'M0112',
            parentId: 'M01',
          },
        ],
      },
    ],
  },
  {
    id: 'K',
    name: 'HEAD OFFICE',
    sortNo: 'K',
    parentId: '0',
  },
  {
    id: 'L',
    name: 'PMO',
    sortNo: 'L',
    parentId: '0',
  }
];
